### ISSUE TITLE
Quiet (or percentage done) Output option

### ISSUE THREAD

**Issue by iampryan** [venominfosec/SecretsChecker#1]
Instead of having a default of the progress going to stdout, it would be great if there was a -q (quite) or a multiples of v option (-vv) to increase or minimize the amount of verbosity.

**Comment by venominfosec** [comment]
This is now present as of v1.4.0 (commit 565c2eb03ac53d509f0947077747c044b144863c).

It can be specified using the `--quiet` argument.
